[package]
name = "rs-iceq"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1", features = ["fs", "time"] }
chrono = "0.4"
rfd = "0.14"
